### ISSUE TITLE
Proper way to change the default_launch_handler

### ISSUE THREAD

**Issue by cteodorski** [patricksmith/pylexa#1]
If I don't want my default_launch_handler to say "Launching...", what is the proper way to handle that?  I'm trying to write a skill that handles A, B and C.  And if a letter is not specified it assumes A.    I think I want the default_launch_handler for that...

**Comment by patricksmith** [comment]
You can use the `handle_launch_request` decorator to define a custom launch handler instead of using the default launch handler. If you'd like to use the same method to handle the launch request and an intent, you can stack the decorators. For example, to handle the `A` intent and launch with the same method you could write:

``` python
@handle_intent('A')
@handle_launch_request
def handle_start_message(request):
    pass
```

**Comment by cteodorski** [comment]
Thank you for the assistance.  Btw, love this library, I couldn't have made my first skill without it.
