### ISSUE TITLE
Wait For Command After Launch

### ISSUE THREAD

**Issue by Shugabuga** [patricksmith/pylexa#2]
I am working on a skill and want, when opened without query, to ask, and listen for, a query. So if I tell Alexa `Alexa, open SkillName`, it will then say a message (like `Welcome to SkillName! What do you need?`) and listen for more input.

Current code (from #1)
```
@handle_intent('A')
@handle_launch_request
def handle_start_message(request):
    return PlainTextSpeech('Welcome to SkillName! What do you need?')
```

**Comment by patricksmith** [comment]
Hi @Shugabuga. The sample code you have there will return some speech, but in order to prompt the user for more input, you have to specify that the session should remain open using the `Response` object directly:

```python
@handle_launch_request
def handle_start_message(request):
    return Response(
        speech=PlainTextSpeech('Welcome to SkillName! What do you need?'), 
        should_end_session=False
    )
```

Then, you'll receive another request within the same session from the user. You can keep data in the session by passing a `dict` in as the `session` keyword argument. 

(For a more complex example using this library, you may want to check out [the code for this Alexa skill that posts to Slack](https://github.com/promptworks/alexa-slack/blob/master/alexa_slack/intent_handlers.py))

**Comment by Shugabuga** [comment]
Forgot to close this.
